listen = "0.0.0.0:6665" # Don't touch this if you running under Docker container

# Message of The Day
# It will be displayed to every player in the Figura menu who is connected to your server
motd = """
[
    {
        "text": "You are connected to "
    },
    {
        "color": "gold",
        "text": "The Sculptor"
    },
    {
        "text": "\nUnofficial Backend V2 for Figura\n\n"
    },
    {
        "clickEvent": {
            "action": "open_url",
            "value": "https://github.com/shiroyashik/sculptor"
        },
        "text": "Please "
    },
    {
        "clickEvent": {
            "action": "open_url",
            "value": "https://github.com/shiroyashik/sculptor"
        },
        "color": "gold",
        "text": "Star",
        "underlined": true
    },
    {
        "clickEvent": {
            "action": "open_url",
            "value": "https://github.com/shiroyashik/sculptor"
        },
        "text": " me on GitHub!\n\n"
    }
]
"""

[limitations]
maxAvatarSize = 100000
maxAvatars = 10

[advancedUsers.66004548-4de5-49de-bade-9c3933d8eb97]
username = "Shiroyashik"
authSystem = "elyby"
special = [0,0,0,1,0,0] # 6
pride = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] # 25

# Your nickname here
# [advancedUsers.your uuid here]
# username = "Bot"
# authSystem = "mojang" # can be: mojang, elyby, internal (cant be authenticated)
# special = [0,1,0,0,0,0] # and set badges what you want! :D
# pride = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

# you can create an unlimited number of "advancedUsers" for any users.